title: "Oluwaleke's Profile"
author: "Oluwaleke Oni"
description: "My Data Science Journey"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "Oluwaleke_Oni_CV", title: "Resume", icon: home}
  - {title: "Profile", url: https://oluwaleke.github.io/Oluwaleke/}
  - {title: "About Me", url: https://sites.google.com/view/oluwalekeoni/home?authuser=0}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:oluwalekeoni@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/Oluwaleke"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/Oni Oluwaleke Enoch"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
